In [1]:
import numpy as np
import pandas as pd

In [2]:
data = [
    ['Nissan', 'Stanza', 1991, 138, 4, 'MANUAL', 'sedan', 2000],
    ['Hyundai', 'Sonata', 2017, None, 4, 'AUTOMATIC', 'Sedan', 27150],
    ['Lotus', 'Elise', 2010, 218, 4, 'MANUAL', 'convertible', 54990],
    ['GMC', 'Acadia',  2017, 194, 4, 'AUTOMATIC', '4dr SUV', 34450],
    ['Nissan', 'Frontier', 2017, 261, 6, 'MANUAL', 'Pickup', 32340],
]

columns = [
    'Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
    'Transmission Type', 'Vehicle_Style', 'MSRP'
]

In [3]:
df = pd.DataFrame(data, columns=columns)

In [4]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [5]:
df.Year

0    1991
1    2017
2    2010
3    2017
4    2017
Name: Year, dtype: int64

In [6]:
df[['Year', 'Make']]

   Year     Make
0  1991   Nissan
1  2017  Hyundai
2  2010    Lotus
3  2017      GMC
4  2017   Nissan

In [7]:
df.head(n=3)

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990

In [8]:
df['id'] = [1, 2, 3, 4, 5]

In [9]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000,1
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,2
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990,3
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450,4
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340,5

In [10]:
del df.id

AttributeError: 'DataFrame' object has no attribute 'id'

In [11]:
del df['id']

In [12]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [13]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [14]:
df.loc[1]

Make                   Hyundai
Model                   Sonata
Year                      2017
Engine HP                  NaN
Engine Cylinders             4
Transmission Type    AUTOMATIC
Vehicle_Style            Sedan
MSRP                     27150
Name: 1, dtype: object

In [15]:
pd._version_

AttributeError: module 'pandas' has no attribute '_version_'

In [16]:
pd.__version__

'3.0.5'

In [17]:
pd.__version__

'3.0.5'

In [18]:
df.index = ['a', 'b', 'c', 'd']

ValueError: Length mismatch: Expected axis has 5 elements, new values have 4 elements

In [19]:
df.index = ['a', 'b', 'c', 'd', 'f']

In [20]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
a,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
b,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
c,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
d,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
f,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [21]:
df.loc['a']

Make                 Nissan
Model                Stanza
Year                   1991
Engine HP             138.0
Engine Cylinders          4
Transmission Type    MANUAL
Vehicle_Style         sedan
MSRP                   2000
Name: a, dtype: object

In [22]:
df.loc[1]

KeyError: 1

In [23]:
df.loc[['a', 'b']]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
a,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
b,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150

In [24]:
df.iloc[1]

Make                   Hyundai
Model                   Sonata
Year                      2017
Engine HP                  NaN
Engine Cylinders             4
Transmission Type    AUTOMATIC
Vehicle_Style            Sedan
MSRP                     27150
Name: b, dtype: object

In [25]:
df.loc[1]

KeyError: 1

In [26]:
df.reset_index

<bound method DataFrame.reset_index of       Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
a   Nissan    Stanza  1991      138.0                 4            MANUAL
b  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC
c    Lotus     Elise  2010      218.0                 4            MANUAL
d      GMC    Acadia  2017      194.0                 4         AUTOMATIC
f   Nissan  Frontier  2017      261.0                 6            MANUAL

  Vehicle_Style   MSRP
a         sedan   2000
b         Sedan  27150
c   convertible  54990
d       4dr SUV  34450
f        Pickup  32340  >

In [27]:
df = df.reset_index(drop=true)

NameError: name 'true' is not defined

In [28]:
df = df.reset_index(drop=True)

In [29]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [30]:
df['Engine HP'] * 2

0    276.0
1      NaN
2    436.0
3    388.0
4    522.0
Name: Engine HP, dtype: float64

In [31]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [32]:
df['Year'] >= 2015

0    False
1     True
2    False
3     True
4     True
Name: Year, dtype: bool

In [33]:
df.Year >= 2015

0    False
1     True
2    False
3     True
4     True
Name: Year, dtype: bool

In [34]:
df.Engine HP * 2

SyntaxError: invalid syntax (1547458523.py, line 1)

In [35]:
df.[['Year', 'MSRP']]

SyntaxError: invalid syntax (2295969813.py, line 1)

In [36]:
df.[['Year', 'MSRP']] * 2

SyntaxError: invalid syntax (2179231991.py, line 1)

In [37]:
df[['Year', 'MSRP']]

   Year   MSRP
0  1991   2000
1  2017  27150
2  2010  54990
3  2017  34450
4  2017  32340

In [38]:
df[['Year', 'MSRP']] * 2

   Year    MSRP
0  3982    4000
1  4034   54300
2  4020  109980
3  4034   68900
4  4034   64680

In [39]:
df.Year >= 2015

0    False
1     True
2    False
3     True
4     True
Name: Year, dtype: bool

In [40]:
df[
    df.Year >= 2015
]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [41]:
df[
    (df.Year >= 2015) and (df.Make == 'Nissan')
]

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [42]:
df[
    ((df.Year >= 2015) and (df.Make == 'Nissan'))
]

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [43]:
df[
    (df.Year >= 2015) & (df.Make == 'Nissan')
]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [44]:
df[
    (df.Year >= 2015) & (df.Make == 'Nissan')
]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [45]:
df[
    (df.Year >= 2015) or (df.Make == 'Nissan')
]

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [46]:
df[
    (df.Year >= 2015) | (df.Make == 'Nissan')
]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [1]:
df

NameError: name 'df' is not defined

In [2]:
import numpy as np
import pandas as pd

data = [
    ['Nissan', 'Stanza', 1991, 138, 4, 'MANUAL', 'sedan', 2000],
    ['Hyundai', 'Sonata', 2017, None, 4, 'AUTOMATIC', 'Sedan', 27150],
    ['Lotus', 'Elise', 2010, 218, 4, 'MANUAL', 'convertible', 54990],
    ['GMC', 'Acadia',  2017, 194, 4, 'AUTOMATIC', '4dr SUV', 34450],
    ['Nissan', 'Frontier', 2017, 261, 6, 'MANUAL', 'Pickup', 32340],
]

columns = [
    'Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
    'Transmission Type', 'Vehicle_Style', 'MSRP'
]

In [3]:
df = pd.DataFrame(data, columns=columns)

In [4]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [5]:
df['Engine HP'].count()

np.int64(4)

In [6]:
df.count()

Make                 5
Model                5
Year                 5
Engine HP            4
Engine Cylinders     5
Transmission Type    5
Vehicle_Style        5
MSRP                 5
dtype: int64

In [7]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [8]:
df.describe()

              Year  Engine HP  Engine Cylinders          MSRP
count     5.000000    4.00000          5.000000      5.000000
mean   2010.400000  202.75000          4.400000  30186.000000
std      11.260551   51.29896          0.894427  18985.044904
min    1991.000000  138.00000          4.000000   2000.000000
25%    2010.000000  180.00000          4.000000  27150.000000
50%    2017.000000  206.00000          4.000000  32340.000000
75%    2017.000000  228.75000          4.000000  34450.000000
max    2017.000000  261.00000          6.000000  54990.000000

In [9]:
df.count()

Make                 5
Model                5
Year                 5
Engine HP            4
Engine Cylinders     5
Transmission Type    5
Vehicle_Style        5
MSRP                 5
dtype: int64

In [10]:
pandas __version__

SyntaxError: invalid syntax (3715627234.py, line 1)

In [11]:
pd __version__

SyntaxError: invalid syntax (1437239774.py, line 1)

In [12]:
pd.__version__

'3.0.5'